name: Test Workflow
on: workflow_dispatch
jobs:
  test-workflow-job:
    name: Test Workflow Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@40a16ebeed7da831425b665e600750cb36b38d06
